#!/usr/bin/with-contenv bash

fix_config() {
    BT_PORT=${BT_PORT:-34567}
    WEBUI_PORT=${WEBUI_PORT:-8070}
    if [ ! -s /data/config/qBittorrent.conf ]; then
        echo "Initializing qBittorrent configuration..."
        cat > /data/config/qBittorrent.conf << EOF
[General]
ported_to_new_savepath_system=true

[AutoRun]
enabled=true
program=cg_qbt.sh \"%N\" \"%F\" \"%C\" \"%Z\" \"%I\" \"%L\"

[BitTorrent]
Session\AddExtensionToIncompleteFiles=true
Session\AlternativeGlobalDLSpeedLimit=50000
Session\AlternativeGlobalUPSpeedLimit=0
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\MaxConnections=-1
Session\MaxConnectionsPerTorrent=-1
Session\MaxUploads=-1
Session\MaxUploadsPerTorrent=-1

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Preferences]
Connection\Interface=
Connection\PortRangeMin=${BT_PORT}
Connection\UseUPnP=false
Downloads\SavePath=/data/downloads/
General\Locale=zh
General\UseRandomPort=false
Queueing\QueueingEnabled=true
Queueing\MaxActiveDownloads=5
Queueing\MaxActiveTorrents=-1
Queueing\MaxActiveUploads=-1
WebUI\Address=*
WebUI\AlternativeUIEnabled=false
WebUI\CSRFProtection=false
WebUI\Enabled=true
WebUI\LocalHostAuth=false
WebUI\Port=${WEBUI_PORT}
EOF
  fi
    echo "Overriding required parameters..."
    sed -i "{
        s!ported_to_new_savepath_system.*!ported_to_new_savepath_system=true!g;
        s!Connection\\\PortRangeMin=.*!Connection\\\PortRangeMin=${BT_PORT}!g;
        s!WebUI\\\Enabled=.*!WebUI\\\Enabled=true!g;
        s!WebUI\\\Port=.*!WebUI\\\Port=${WEBUI_PORT}!g;
        s!WebUI\\\LocalHostAuth=.*!WebUI\\\LocalHostAuth=false!g;
    }" /data/config/qBittorrent.conf
  if [ ! -s /data/config/categories.json ]; then
        echo "Initializing qBittorrent configuration..."
        cat > /data/config/categories.json << EOF
{
    "1.pt-down": {
        "save_path": "/data/downloads/pt-down"
    },
    "2.pt-up": {
        "save_path": "/data/downloads/pt-up"
    },
    "3.pt-mt": {
        "save_path": "/data/downloads/pt-mt"
    },
    "4.pt-ttg": {
        "save_path": "/data/downloads/pt-ttg"
    },
    "98t-c": {
        "save_path": ""
    }
}
EOF
  fi
}

fix_config 2>&1 | sed "s#^#cont-init: info: $(realpath $0): \1#g"
