# Copyright (c) 2020-2021 cgkings
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Docker Images Publish

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - 'main'

env:
  ## 镜像名，也是git仓库中的文件夹名
  IMAGE_NAME: qbittorrent
  ## Dockerfile文件名称，在这里修改
  DOCKERFILE_NAME: Dockerfile

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    # - name: Marker version and time
    #   id: getVersion
    #   run: |
    #     sed -i "s@COMMIT_HASH@$(git rev-parse --short HEAD)@" rootfs/Aria2-Pro
    #     sed -i "s@DATE_TIME@$(date +"%Y/%m/%d %H:%M")@" rootfs/Aria2-Pro
    #     cat rootfs/Aria2-Pro
    #     echo "::set-output name=time::$(date +"%Y%m%d%H%M")"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ${{ env.IMAGE_NAME }}/${{ env.DOCKERFILE_NAME }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/qbittorrent:${{ steps.date.outputs.today }}
    #   tags: ${{ secrets.DOCKERHUB_USERNAME }}/qbittorrent:${{ steps.date.outputs.today }}